name: Generate Subscription

on:
  workflow_dispatch:
  schedule:
    - cron: '0 21 * * *'  # 00:00 Moscow (UTC+3)

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0 # saxo для pull --rebase

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install aiohttp requests psutil rich art

      - name: Run Generator
        run: python GENERATOR.py

      - name: Commit and push if changed
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "actions@github.com"
          git add Molestunnels.txt Molestunnels.base64.txt
          # Если нет изменений — выходим без ошибки
          git diff --cached --quiet && exit 0
          git commit -a -m "Auto update tunnels"
          # Проверяем изменения еще раз
          git pull --rebase origin main
          git push origin main
